eClaims/Models/ClaimInfo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eClaims.Models
{
    public class ClaimInfo : PageInfo
    {
        public int iClaimId { get; set; } = 1;

        [Required(ErrorMessage = "Date Of Transaction is required.")]
        [Display(Name = "Date Of Transaction")]
        public DateTime dtTrnDate { get; set; }

        [Required(ErrorMessage = "Cost Center is required.")]
        public int iCostCtr { get; set; }

        [Display(Name = "Cost Center")]
        public string vaCostCtr { get; set; }

        [Required(ErrorMessage = "GL Code is required.")]
        public int iGlId { get; set; }

        [Display(Name = "GL Code")]
        public string vaGLCode { get; set; }

        [Required(ErrorMessage = "Description is required.")]
        [Display(Name = "Description")]
        public string vaDesc { get; set; }

        [Required(ErrorMessage = "Currency is required.")]
        public int iCurr { get; set; }

        [Display(Name = "Currency")]
        public string vaCurr { get; set; }

        [Required(ErrorMessage = "Amount is required.")]
        [Display(Name = "Amount")]
        public decimal? mnAmount { get; set; }

        [Display(Name = "GST")]
        public decimal? decGST { get; set; }

        [Display(Name = "GST Amount")]
        public decimal? mnGSTAmt { get; set; }

        [Display(Name = "Exchange Rate")]
        public decimal? decExRate { get; set; }

        [Required(ErrorMessage = "Total Amount is required.")]
        [Display(Name = "Total Amount")]
        public decimal? mnTotalAmt { get; set; }

        public List<SelectListItem> listCostCenter { get; set; }
        public List<SelectListItem> listGlCode { get; set; }
        public List<SelectListItem> listCurrency { get; set; }
    }

    //public class CostCentre
    //{
    //    public int iCostId { get; set; }
    //    public string vaCostDesc { get; set; }
    //}

    //public class GlCode
    //{
    //    public int iGlId { get; set; }
    //    public string vaGlDesc { get; set; }
    //}
}

eClaims/Controllers/ClaimController.cs
using eClaims.Data;
using eClaims.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eClaims.Controllers
{
    public class ClaimController : Controller
    {
        private static ClaimDLL _claimData = new ClaimDLL();
        public ActionResult AddClaim()
        {
            ClaimInfo objClaimInfo = new ClaimInfo();
            objClaimInfo.pageTitle = "Add Claim";
            GetScreenSetup(objClaimInfo);

            return View("ClaimInfo", objClaimInfo);
        }

        public void GetScreenSetup(ClaimInfo objClaimInfo)
        {
            DataTable dtCostCenter = _claimData.GetListofCostCenter();

            DataTable dtGlCode = _claimData.GetListofGlCode();

            DataTable dtCurrency = _claimData.GetListofCurrency();

            objClaimInfo.listCostCenter = new List<SelectListItem>();
            objClaimInfo.listCostCenter = (from DataRow dr in dtCostCenter.Rows
                                           select new SelectListItem()
                                           {
                                               Value = dr["iCostId"].ToString(),
                                               Text = dr["vaDesc"].ToString(),
                                           }).ToList();

            objClaimInfo.listGlCode = new List<SelectListItem>();
            objClaimInfo.listGlCode = (from DataRow dr in dtGlCode.Rows
                                       select new SelectListItem()
                                       {
                                           Value = dr["iGlId"].ToString(),
                                           Text = dr["vaDesc"].ToString(),
                                       }).ToList();

            objClaimInfo.listCurrency = new List<SelectListItem>();
            objClaimInfo.listCurrency = (from DataRow dr in dtCurrency.Rows
                                         select new SelectListItem()
                                         {
                                             Value = dr["iCurr"].ToString(),
                                             Text = dr["vaCurr"].ToString(),
                                         }).ToList();
        }

       [HttpPost]
        public ActionResult AddClaim(ClaimInfo objClaimInfo)
        {
            if (ModelState.IsValid)
            {
                string rtnCode = _claimData.AddNewClaim(objClaimInfo);

                if (rtnCode == "0")
                    return RedirectToAction("SubmittedClaim", "Claim");
            }

            GetScreenSetup(objClaimInfo);

            return View("ClaimInfo", objClaimInfo);
        }

        public ActionResult ViewClaim(int claimId)
        {
            ClaimInfo objClaimInfo = new ClaimInfo();

            DataTable dtClaimInfo = _claimData.GetClaimInfo(claimId);

            if (dtClaimInfo != null && dtClaimInfo.Rows.Count > 0 && Convert.ToInt32(dtClaimInfo.Rows[0]["iClaimId"].ToString()) == claimId)
            {
                objClaimInfo.pageMode = 2;//view
                objClaimInfo.pageTitle = "View Claim";
                objClaimInfo.iClaimId = claimId;
                objClaimInfo.decExRate = decimal.Parse(dtClaimInfo.Rows[0]["decExRate"].ToString());
                objClaimInfo.decGST = decimal.Parse(dtClaimInfo.Rows[0]["decGST"].ToString());
                objClaimInfo.dtTrnDate = Convert.ToDateTime(dtClaimInfo.Rows[0]["dtTrnDate"].ToString());
                objClaimInfo.mnAmount = decimal.Parse(dtClaimInfo.Rows[0]["mnAmt"].ToString());
                objClaimInfo.mnTotalAmt = decimal.Parse(dtClaimInfo.Rows[0]["mnTotalAmt"].ToString());
                objClaimInfo.vaCostCtr = dtClaimInfo.Rows[0]["vaCostCtr"].ToString();
                objClaimInfo.vaCurr = dtClaimInfo.Rows[0]["vaCurr"].ToString();
                objClaimInfo.vaDesc = dtClaimInfo.Rows[0]["vaDesc"].ToString();
                objClaimInfo.vaGLCode = dtClaimInfo.Rows[0]["vaGLCode"].ToString();
                objClaimInfo.mnGSTAmt = decimal.Parse(dtClaimInfo.Rows[0]["mnGSTAmt"].ToString());
            }

            return View("ClaimInfo", objClaimInfo);
        }

        public ActionResult SubmittedClaim()
        {
            GridView objGridView = new GridView();
            objGridView.SortDefaultValue = "ClaimId";
            objGridView.SortValue = objGridView.SortDefaultValue + " DESC";

            SessionModel.SessGridView = objGridView;
            GridViewController objGridViewController = new GridViewController();
            objGridViewController.GridViewListingReturn("CL01");

            return View();
        }

        [HttpPost]
        public ActionResult PreviewSubmissionClaim(string slctClaim)
        {
            GlobalModel objGlobalInfo = new GlobalModel();

            UserInfo objUsrInfo = new UserInfo();
            BankInfo objBankInfo = new BankInfo();
            PageInfo objPageInfo = new PageInfo();

            objPageInfo.pageTitle = "Expense Claims";

            DataTable dtUserBankInfo = _claimData.GetUserBankInfo(2);

            if (dtUserBankInfo != null && dtUserBankInfo.Rows.Count > 0)
            {
                objUsrInfo.vaFullName = dtUserBankInfo.Rows[0]["vaFullName"].ToString();
                objUsrInfo.vaBranchCode = dtUserBankInfo.Rows[0]["vaBranchCode"].ToString();

                objBankInfo.vaBankCode = dtUserBankInfo.Rows[0]["vaBankCode"].ToString();
                objBankInfo.vaBankAccName = dtUserBankInfo.Rows[0]["vaBankAccName"].ToString();
                objBankInfo.vaBankAccNo = dtUserBankInfo.Rows[0]["vaBankAccNo"].ToString();
            }

            objGlobalInfo.clsPageInfo = objPageInfo;
            objGlobalInfo.clsUserInfo = objUsrInfo;
            objGlobalInfo.clsBankInfo = objBankInfo;

            GridView objGridView = new GridView();
            objGridView.SortDefaultValue = "ClaimId";
            objGridView.StoreProcParam = slctClaim;

            SessionModel.SessGridView = objGridView;
            GridViewController objGridViewController = new GridViewController();
            objGridViewController.GridViewListingReturn("CL02");


            return View(objGlobalInfo);
        }
    }
}

eClaims/Controllers/PartialController.cs
using eClaims.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eClaims.Controllers
{
    public class PartialController : Controller
    {
        // GET: Partial
        public ActionResult GridView()
        {

            GridView objGridView = SessionModel.SessGridView;

            return PartialView(objGridView);
        }
    }
}

eClaims/Views/Claim/PreviewSubmissionClaim.cshtml
@model eClaims.Models.GlobalModel


<div class="page">
    <div class="page-content">
        <div class="sdk">
            <div class="sdk-container">
                <div class="sdk-main">
                    <div class="container body-content">
                        <div class="contentAndNav">
                            <div class="card">
                                <div class="card-header">
                                    @Model.clsPageInfo.pageTitle
                                </div>
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col-lg-12 col-md-12 col-xs-12 col-sm-12 textfield" id="rowClaimcInfo">
                                            <div class='labelMainPage'>
                                                <span id='spanBasicInfo'>User Informations</span>
                                            </div>
                                            <div class='toggled_content'>
                                                <br />

                                                <div class="row">
                                                    <div class="col-lg-6 col-md-6 col-xs-12 col-sm-12 textfield">
                                                        <div class="row">
                                                            <div class="col-lg-4 col-md-4 col-xs-12 col-sm-12 textfield add-colon">
                                                                <p>@Html.DisplayNameFor(model => model.clsUserInfo.vaFullName)<span class="asterisk" style="color:Red; display:none;">*</span></p>
                                                            </div>
                                                            <div class="col-lg-8 col-md-8 col-xs-12 col-sm-12 textfield">
                                                                @Html.TextBoxFor(model => model.clsUserInfo.vaFullName, new { @class = "form-control", autocomplete = "off", @readonly = "true" })
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="col-lg-6 col-md-6 col-xs-12 col-sm-12 textfield">
                                                        <div class="row">
                                                            <div class="col-lg-4 col-md-4 col-xs-12 col-sm-12 textfield add-colon">
                                                                <p>@Html.DisplayNameFor(model => model.clsUserInfo.vaBranchCode)<span class="asterisk" style="color:Red; display:none;">*</span></p>
                                                            </div>
                                                            <div class="col-lg-8 col-md-8 col-xs-12 col-sm-12 textfield">
                                                                @Html.TextBoxFor(model => model.clsUserInfo.vaBranchCode, new { @class = "form-control", autocomplete = "off", @readonly = "true" })
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>

                                                <div class="row">
                                                    <div class="col-lg-6 col-md-6 col-xs-12 col-sm-12 textfield">
                                                        <div class="row">
                                                            <div class="col-lg-4 col-md-4 col-xs-12 col-sm-12 textfield add-colon">
                                                                <p>@Html.DisplayNameFor(model => model.clsBankInfo.vaBankCode)<span class="asterisk" style="color:Red; display:none;">*</span></p>
                                                            </div>
                                                            <div class="col-lg-8 col-md-8 col-xs-12 col-sm-12 textfield">
                                                                @Html.TextBoxFor(model => model.clsBankInfo.vaBankCode, new { @class = "form-control", autocomplete = "off", @readonly = "true" })
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="col-lg-6 col-md-6 col-xs-12 col-sm-12 textfield">
                                                        <div class="row">
                                                            <div class="col-lg-4 col-md-4 col-xs-12 col-sm-12 textfield add-colon">
                                                                <p>@Html.DisplayNameFor(model => model.clsBankInfo.vaBankAccNo)<span class="asterisk" style="color:Red; display:none;">*</span></p>
                                                            </div>
                                                            <div class="col-lg-8 col-md-8 col-xs-12 col-sm-12 textfield">
                                                                @Html.TextBoxFor(model => model.clsBankInfo.vaBankAccNo, new { @class = "form-control", autocomplete = "off", @readonly = "true" })
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>

                                                <div class="row">
                                                    <div class="col-lg-6 col-md-6 col-xs-12 col-sm-12 textfield">
                                                        <div class="row">
                                                            <div class="col-lg-4 col-md-4 col-xs-12 col-sm-12 textfield add-colon">
                                                                <p>@Html.DisplayNameFor(model => model.clsBankInfo.vaBankAccName)<span class="asterisk" style="color:Red; display:none;">*</span></p>
                                                            </div>
                                                            <div class="col-lg-8 col-md-8 col-xs-12 col-sm-12 textfield">
                                                                @Html.TextBoxFor(model => model.clsBankInfo.vaBankAccName, new { @class = "form-control", autocomplete = "off", @readonly = "true" })
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="col-lg-6 col-md-6 col-xs-12 col-sm-12 textfield">
                                                        <div class="row">

                                                        </div>
                                                    </div>
                                                </div>

                                                <br />

                                                @{
                                                    Html.RenderAction("GridView", "Partial");
                                                }
                                            </div>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

eClaims/Views/Claim/SubmittedClaim.cshtml
<div class="page">
    <div class="page-content">
        <div class="sdk">
            <div class="sdk-container">
                <div class="sdk-main">
                    <div class="container body-content">
                        <div class="contentAndNav">
                            <div class="col-lg-12 col-md-12 col-xs-12 col-sm-12 textfield" id="rowClaimcInfo">
                                <div class='toggled_content'>
                                    <br />

                                    @{
                                        Html.RenderAction("GridView", "Partial");
                                    }

                                    <br />
                                    <form action="PreviewSubmissionClaim" method="post">
                                        <input type="hidden" name="slctClaim" class="slctClaim" />
                                        <div class="col-lg-12 col-md-12 col-xs-12 col-sm-12" ">
                                            <button type="submit" class="btn btn-primary" id="btnPrev" disabled>Preview Submission</button>

                                        </div>
                                    </form>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(".clsCheckBox").change(function () {
        var row = $(this).attr('row');
        var tdClsName = '.row_' + row.toString();
        var claimId = $(tdClsName.toString()).attr('value');
        var slctClaimVal = $('.slctClaim').val();

        if (this.checked && slctClaimVal == '') {
            slctClaimVal = claimId;
        }

        else if (this.checked && slctClaimVal != '') {
            slctClaimVal = slctClaimVal + ',' + claimId;
        }

        else if (!this.checked && slctClaimVal.indexOf(',') != -1) {
            claimId = ',' + claimId;
            slctClaimVal = slctClaimVal.replace(claimId,'');
        }

        else {
            slctClaimVal = slctClaimVal.replace(claimId, '');
        }

        $('.slctClaim').val(slctClaimVal);

        if (slctClaimVal == '')
            $("#btnPrev").prop("disabled", true);
        else
            $("#btnPrev").prop("disabled", false);
    });

</script>